[package]
name = "pragmatic-segmenter"
version = "0.1.0"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onig = "6"
regex = "1"
aho-corasick = "0.7"
unic-ucd-case = "0.9.0"
