on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt --all -- --check
    - run: cargo build

      # NOTE: Allow test fail for now
    - run: cargo test || true

    - run: cargo clippy -- -D warnings
